name: Delightfully Discombobulated
favicon: null
layout_spectrum: 0.66155
typography_spectrum: 0.06088
title: Random Musings of a Southern Girl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#638a4c'
    - '#fefefe'
    - '#1a3f27'
    - '#91b1aa'
    - '#673316'
  brandStrength: 0.6397121921181679
  lightness: 0.49786584568209946
  saturation: 0.6430236757732928
  rhythmicContrast: 0.05478914454579353
purpose: []
